name: run-tests
on:
  push:
    paths:
      - 'src/**'
      - 'index.ts'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/run-tests.yml'
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        run: npm install -g yarn
      - name: run tests
        run: |
          yarn
          yarn test
